name: tap_hero
description: Tap Hero

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.0.0
  share_plus: ^9.0.0
  simple_animations: ^5.0.2
  window_manager: ^0.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/background/
    - assets/character/
    - assets/boss/
    - assets/elements/
    - assets/audio/

  fonts:
    - family: Gameplay
      fonts:
        - asset: fonts/gameplay.ttf
